// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
type PrismaConfig = {
  schema: string;
  migrations: { path: string };
  datasource: { url: string | undefined };
};

const config: PrismaConfig = {
  schema: "prisma/schema.prisma",
  migrations: { path: "prisma/migrations" },
  datasource: { url: process.env.DATABASE_URL },
};

export default config;
